### ISSUE TITLE
fvec_copy não funciona como o esperado

### ISSUE THREAD

**Issue by hadron13** [Defmc/fvec#1]
![print](https://user-images.githubusercontent.com/62845905/127660599-48a0fc6e-f4d9-410a-b7f8-4f3c329b0140.png)

o vetor com texturas tinha 2 elementos, com chunk_size de 2, mas aparentemente após copiar o elemento end é igual ao start (indicando 0 elementos), e o chunk_size fica com lixo, equal_func e greater_func são definidos como NULL no vetor original, mas apenas o equal_func manteve o valor.

**Comment by Defmc** [comment]
[Problema fixado](https://github.com/Defmc/fvec/commit/7d15f90c029dc06e9698102c99d2deb30cb9134d). `fvec_slice` não estava atualizando `chunk_size` além de não definir valor de `equal_func` no vetor alvo.
